// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ws_connect
SEXP ws_connect(std::string url);
RcppExport SEXP webrockets_ws_connect(SEXP urlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type url(urlSEXP);
    rcpp_result_gen = Rcpp::wrap(ws_connect(url));
    return rcpp_result_gen;
END_RCPP
}
// ws_receive_one
std::string ws_receive_one(SEXP ws_ptr, int frequency);
RcppExport SEXP webrockets_ws_receive_one(SEXP ws_ptrSEXP, SEXP frequencySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ws_ptr(ws_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type frequency(frequencySEXP);
    rcpp_result_gen = Rcpp::wrap(ws_receive_one(ws_ptr, frequency));
    return rcpp_result_gen;
END_RCPP
}
// ws_receive_multiple
std::vector<std::string> ws_receive_multiple(SEXP ws_ptr, unsigned int eventlimit);
RcppExport SEXP webrockets_ws_receive_multiple(SEXP ws_ptrSEXP, SEXP eventlimitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ws_ptr(ws_ptrSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type eventlimit(eventlimitSEXP);
    rcpp_result_gen = Rcpp::wrap(ws_receive_multiple(ws_ptr, eventlimit));
    return rcpp_result_gen;
END_RCPP
}
// ws_receive
std::string ws_receive(SEXP ws_ptr, int timeout);
RcppExport SEXP webrockets_ws_receive(SEXP ws_ptrSEXP, SEXP timeoutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ws_ptr(ws_ptrSEXP);
    Rcpp::traits::input_parameter< int >::type timeout(timeoutSEXP);
    rcpp_result_gen = Rcpp::wrap(ws_receive(ws_ptr, timeout));
    return rcpp_result_gen;
END_RCPP
}
