# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' ws_close
#'
#' Close a socket connection (DOES NOT WORK PROPERLY)
#'
#' @param ws_ptr websocket ptr object.
NULL

#' Connect to websocket
#'
#' @param url URL for websocket server
#' @export
ws_connect <- function(url) {
    .Call('webrockets_ws_connect', PACKAGE = 'webrockets', url)
}

#' ws_receive_one
#'
#' Query websocket until one message received
#'
#' @param ws_ptr pointer from \code{\link{ws_connect}}
#' @param frequency time before timing out each time server is queried
#' @export
#' @return string with message from server
#' @export
#' @examples
#' \dontrun{
#'     con <- ws_connect("ws://localhost:5006/") # Need to have websocket server
#'     ws_receive_one(con, 5) # returns one message
#' }
#'
ws_receive_one <- function(ws_ptr, frequency = 5L) {
    .Call('webrockets_ws_receive_one', PACKAGE = 'webrockets', ws_ptr, frequency)
}

#' ws_receive_multiple
#'
#' Consume n events
#' @param ws_ptr pointer from \code{\link{ws_connect}}
#' @param eventlimit limit of events
#' @return list of strings with each message
#' @export
#' @examples
#'
#' \dontrun{
#'     con <- ws_connect("ws://localhost:5006/") # Need to have websocket server
#'     ws_receive_multiple(con, 3) # returns 3 messages
#' }
ws_receive_multiple <- function(ws_ptr, eventlimit) {
    .Call('webrockets_ws_receive_multiple', PACKAGE = 'webrockets', ws_ptr, eventlimit)
}

#' ws_receive
#'
#' Consume one message within timeout
#'
#' @param ws_ptr pointer from \code{\link{ws_connect}}
#' @param timeout time in milliseconds before timing out, see details
#' @details If timout is set to a negative number, the process should
#' block until a message arrives. If set to 0, no blocking is performed --
#' a message is returned if it is there.  If set to a positive value,
#' the function will wait until there is a message or a timeout
#' @return one message, if one occurs within timeout. otherwise, empty string
#' @export
#' @examples
#'
#' \dontrun{
#'     con <- ws_connect("ws://localhost:5006/") # Need to have websocket server
#'     ws_receive(con, 5)
#' }
ws_receive <- function(ws_ptr, timeout = 5L) {
    .Call('webrockets_ws_receive', PACKAGE = 'webrockets', ws_ptr, timeout)
}

#' ws_send
#'
ws_send <- function(ws_ptr, message) {
    invisible(.Call('webrockets_ws_send', PACKAGE = 'webrockets', ws_ptr, message))
}

