# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Connect to websocket
#'
#' @param url ws URL
#' @export
ws_connect <- function(url) {
    .Call('webrockets_ws_connect', PACKAGE = 'webrockets', url)
}

#' Consume one message
#'
#' @param ws_ptr pointer from \{code}\link{ws_connect}
#' @param timeout
#' @export
#' @return list of strings with each message
#' @examples
#'
#' \dontrun{
#'     con <- ws_connect(ws://localhost:5006/") # Need to have websocket server
#'     ws_poll(con, 5) # returns one message
#' }
#' @export
ws_poll <- function(ws_ptr, timeout = 5L) {
    .Call('webrockets_ws_poll', PACKAGE = 'webrockets', ws_ptr, timeout)
}

#' Consume n events
#' @param ws_ptr pointer from \{code}\link{ws_connect}
#' @param eventlimit limit of events
#' @return list of strings with each message
#' @examples
#'
#' \dontrun{
#'     con <- ws_connect(ws://localhost:5006/") # Need to have websocket server
#'     ws_poll_list(con, 3) # returns 3 messages
#' }
#' @export
ws_poll_list <- function(ws_ptr, eventlimit) {
    .Call('webrockets_ws_poll_list', PACKAGE = 'webrockets', ws_ptr, eventlimit)
}

#' ws_close
#'
#' Close a socket connection
#'
#' @param Chrome ws ptr object.
#' @export
ws_close <- function(ws_ptr) {
    invisible(.Call('webrockets_ws_close', PACKAGE = 'webrockets', ws_ptr))
}

#' ws_read_one
#'
#' Consume one message within timeout
#'
#' @param ws_ptr pointer from \{code}\link{ws_connect}
#' @param timeout time in milliseconds before timing out, see details
#' @details If timout is set to a negative number, the process should
#' block until a message arrives. If set to 0, no blocking is performed --
#' a message is returned if it is there.  If set to a positive value,
#' the function will wait until there is a message or a timeout
#' @return one message, if one occurs within timeout. otherwise, empty string
#' @examples
#'
#' \dontrun{
#'     con <- ws_connect(ws://localhost:5006/") # Need to have websocket server
#'     ws_read_one(con, 5)
#' }
#' @export
ws_read_one <- function(ws_ptr, timeout = 5L) {
    .Call('webrockets_ws_read_one', PACKAGE = 'webrockets', ws_ptr, timeout)
}

